#!/bin/bash

BASIC_RED="\e[0;31m"
BASIC_GREEN="\e[0;32m"
BASIC_YELLOW="\e[0;33m"
BASIC_CYAN="\e[0;36m"
ENDCOLOR="\e[0m"

run_linter () {
  echo -e "${BASIC_CYAN}🧼 Checking for linting errors in the src directory${ENDCOLOR}"
  bun run lint-staged
  if [[ $? -ne 0 ]]
  then
    echo -e "${BASIC_RED}❌ Linting failed.${ENDCOLOR}"
    echo -e "${BASIC_YELLOW}⚠️ Please fix the errors and try again.${ENDCOLOR}"
    exit 1
  fi
}

run_linter

printf "${BASIC_GREEN}❤️‍🔥 This commit has passed the linting checks. Happy coding!${ENDCOLOR}\n"
